// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationAuditLogs = `-- name: GetOrganizationAuditLogs :many
SELECT id, target_project, actor_id, action, ip_address, user_agent, details, created_at FROM public.audit_logs
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrganizationAuditLogsParams struct {
	ActorID int32
	Limit   int32
	Offset  int32
}

// assuming audit logs without target_project or with org projects context.
// For simplicity, let's keep it project-level or actor-level.
func (q *Queries) GetOrganizationAuditLogs(ctx context.Context, arg GetOrganizationAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getOrganizationAuditLogs, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TargetProject,
			&i.ActorID,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectAuditLogs = `-- name: GetProjectAuditLogs :many
SELECT id, target_project, actor_id, action, ip_address, user_agent, details, created_at FROM public.audit_logs
WHERE target_project = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetProjectAuditLogsParams struct {
	TargetProject pgtype.Text
	Limit         int32
	Offset        int32
}

func (q *Queries) GetProjectAuditLogs(ctx context.Context, arg GetProjectAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getProjectAuditLogs, arg.TargetProject, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TargetProject,
			&i.ActorID,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, account_id, token, expires_at, revoked, created_at, updated_at FROM public.refresh_tokens
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO public.audit_logs (target_project, actor_id, action, ip_address, user_agent, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, target_project, actor_id, action, ip_address, user_agent, details, created_at
`

type InsertAuditLogParams struct {
	TargetProject pgtype.Text
	ActorID       int32
	Action        string
	IpAddress     pgtype.Text
	UserAgent     pgtype.Text
	Details       []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.TargetProject,
		arg.ActorID,
		arg.Action,
		arg.IpAddress,
		arg.UserAgent,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TargetProject,
		&i.ActorID,
		&i.Action,
		&i.IpAddress,
		&i.UserAgent,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO public.refresh_tokens (account_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token, expires_at, revoked, created_at, updated_at
`

type InsertRefreshTokenParams struct {
	AccountID int32
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.AccountID, arg.Token, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE public.refresh_tokens
SET revoked = true, updated_at = now()
WHERE account_id = $1 AND revoked = false
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, accountID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE public.refresh_tokens
SET revoked = true, updated_at = now()
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}
