// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project (project_ref, project_name, organization_id, status, jwt_secret, cloud_provider, region)
VALUES ($1, $2, $3, 'PROVISIONING', $4, $5, $6)
RETURNING id, project_ref, project_name, organization_id, status, cloud_provider, region, jwt_secret, created_at, updated_at, docker_compose_path, docker_network_name, postgres_port, kong_http_port, kong_https_port, anon_key, service_role_key, provisioned_at
`

type CreateProjectParams struct {
	ProjectRef     string
	ProjectName    string
	OrganizationID int32
	JwtSecret      string
	CloudProvider  string
	Region         string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProjectRef,
		arg.ProjectName,
		arg.OrganizationID,
		arg.JwtSecret,
		arg.CloudProvider,
		arg.Region,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectRef,
		&i.ProjectName,
		&i.OrganizationID,
		&i.Status,
		&i.CloudProvider,
		&i.Region,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DockerComposePath,
		&i.DockerNetworkName,
		&i.PostgresPort,
		&i.KongHttpPort,
		&i.KongHttpsPort,
		&i.AnonKey,
		&i.ServiceRoleKey,
		&i.ProvisionedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE project_ref = $1
`

func (q *Queries) DeleteProject(ctx context.Context, projectRef string) error {
	_, err := q.db.Exec(ctx, deleteProject, projectRef)
	return err
}

const getProjectByRef = `-- name: GetProjectByRef :one
SELECT id, project_ref, project_name, organization_id, status, cloud_provider, region, jwt_secret, created_at, updated_at, docker_compose_path, docker_network_name, postgres_port, kong_http_port, kong_https_port, anon_key, service_role_key, provisioned_at
FROM project
WHERE project_ref = $1
`

func (q *Queries) GetProjectByRef(ctx context.Context, projectRef string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByRef, projectRef)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectRef,
		&i.ProjectName,
		&i.OrganizationID,
		&i.Status,
		&i.CloudProvider,
		&i.Region,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DockerComposePath,
		&i.DockerNetworkName,
		&i.PostgresPort,
		&i.KongHttpPort,
		&i.KongHttpsPort,
		&i.AnonKey,
		&i.ServiceRoleKey,
		&i.ProvisionedAt,
	)
	return i, err
}

const getProjectsByStatus = `-- name: GetProjectsByStatus :many
SELECT id, project_ref, project_name, organization_id, status, cloud_provider, region, jwt_secret, created_at, updated_at, docker_compose_path, docker_network_name, postgres_port, kong_http_port, kong_https_port, anon_key, service_role_key, provisioned_at
FROM project
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByStatus(ctx context.Context, status string) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ProjectRef,
			&i.ProjectName,
			&i.OrganizationID,
			&i.Status,
			&i.CloudProvider,
			&i.Region,
			&i.JwtSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DockerComposePath,
			&i.DockerNetworkName,
			&i.PostgresPort,
			&i.KongHttpPort,
			&i.KongHttpsPort,
			&i.AnonKey,
			&i.ServiceRoleKey,
			&i.ProvisionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsForAccountId = `-- name: GetProjectsForAccountId :many
SELECT p.id, p.project_ref, p.project_name, p.organization_id, p.status, p.cloud_provider, p.region, p.jwt_secret, p.created_at, p.updated_at, p.docker_compose_path, p.docker_network_name, p.postgres_port, p.kong_http_port, p.kong_https_port, p.anon_key, p.service_role_key, p.provisioned_at
FROM organization_membership om
         JOIN project p on om.organization_id = p.organization_id
WHERE account_id = $1
`

func (q *Queries) GetProjectsForAccountId(ctx context.Context, accountID int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsForAccountId, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ProjectRef,
			&i.ProjectName,
			&i.OrganizationID,
			&i.Status,
			&i.CloudProvider,
			&i.Region,
			&i.JwtSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DockerComposePath,
			&i.DockerNetworkName,
			&i.PostgresPort,
			&i.KongHttpPort,
			&i.KongHttpsPort,
			&i.AnonKey,
			&i.ServiceRoleKey,
			&i.ProvisionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectInfrastructure = `-- name: UpdateProjectInfrastructure :one
UPDATE project
SET docker_compose_path = $2,
    docker_network_name = $3,
    postgres_port = $4,
    kong_http_port = $5,
    kong_https_port = $6,
    anon_key = $7,
    service_role_key = $8,
    provisioned_at = now(),
    updated_at = now()
WHERE project_ref = $1
RETURNING id, project_ref, project_name, organization_id, status, cloud_provider, region, jwt_secret, created_at, updated_at, docker_compose_path, docker_network_name, postgres_port, kong_http_port, kong_https_port, anon_key, service_role_key, provisioned_at
`

type UpdateProjectInfrastructureParams struct {
	ProjectRef        string
	DockerComposePath pgtype.Text
	DockerNetworkName pgtype.Text
	PostgresPort      pgtype.Int4
	KongHttpPort      pgtype.Int4
	KongHttpsPort     pgtype.Int4
	AnonKey           pgtype.Text
	ServiceRoleKey    pgtype.Text
}

func (q *Queries) UpdateProjectInfrastructure(ctx context.Context, arg UpdateProjectInfrastructureParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectInfrastructure,
		arg.ProjectRef,
		arg.DockerComposePath,
		arg.DockerNetworkName,
		arg.PostgresPort,
		arg.KongHttpPort,
		arg.KongHttpsPort,
		arg.AnonKey,
		arg.ServiceRoleKey,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectRef,
		&i.ProjectName,
		&i.OrganizationID,
		&i.Status,
		&i.CloudProvider,
		&i.Region,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DockerComposePath,
		&i.DockerNetworkName,
		&i.PostgresPort,
		&i.KongHttpPort,
		&i.KongHttpsPort,
		&i.AnonKey,
		&i.ServiceRoleKey,
		&i.ProvisionedAt,
	)
	return i, err
}

const updateProjectJwtSecret = `-- name: UpdateProjectJwtSecret :exec
UPDATE project
SET jwt_secret = $1, updated_at = now()
WHERE project_ref = $2
`

type UpdateProjectJwtSecretParams struct {
	JwtSecret  string
	ProjectRef string
}

func (q *Queries) UpdateProjectJwtSecret(ctx context.Context, arg UpdateProjectJwtSecretParams) error {
	_, err := q.db.Exec(ctx, updateProjectJwtSecret, arg.JwtSecret, arg.ProjectRef)
	return err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE project
SET status = $2, updated_at = now()
WHERE project_ref = $1
RETURNING id, project_ref, project_name, organization_id, status, cloud_provider, region, jwt_secret, created_at, updated_at, docker_compose_path, docker_network_name, postgres_port, kong_http_port, kong_https_port, anon_key, service_role_key, provisioned_at
`

type UpdateProjectStatusParams struct {
	ProjectRef string
	Status     string
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus, arg.ProjectRef, arg.Status)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectRef,
		&i.ProjectName,
		&i.OrganizationID,
		&i.Status,
		&i.CloudProvider,
		&i.Region,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DockerComposePath,
		&i.DockerNetworkName,
		&i.PostgresPort,
		&i.KongHttpPort,
		&i.KongHttpsPort,
		&i.AnonKey,
		&i.ServiceRoleKey,
		&i.ProvisionedAt,
	)
	return i, err
}
