// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationMembers = `-- name: GetOrganizationMembers :many
SELECT a.id, a.email, a.username, a.first_name, a.last_name, om.role, om.created_at
FROM organization_membership om
JOIN accounts a ON om.account_id = a.id
WHERE om.organization_id = $1
`

type GetOrganizationMembersRow struct {
	ID        int32
	Email     string
	Username  string
	FirstName pgtype.Text
	LastName  pgtype.Text
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetOrganizationMembers(ctx context.Context, organizationID int32) ([]GetOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, getOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationMembersRow
	for rows.Next() {
		var i GetOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationMembershipByProjectRef = `-- name: GetOrganizationMembershipByProjectRef :one
SELECT om.organization_id, om.account_id, om.role, om.created_at, om.updated_at
FROM organization_membership om
JOIN project p ON om.organization_id = p.organization_id
WHERE p.project_ref = $1 AND om.account_id = $2 LIMIT 1
`

type GetOrganizationMembershipByProjectRefParams struct {
	ProjectRef string
	AccountID  int32
}

func (q *Queries) GetOrganizationMembershipByProjectRef(ctx context.Context, arg GetOrganizationMembershipByProjectRefParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipByProjectRef, arg.ProjectRef, arg.AccountID)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembershipBySlug = `-- name: GetOrganizationMembershipBySlug :one
SELECT om.organization_id, om.account_id, om.role, om.created_at, om.updated_at
FROM organization_membership om
JOIN organizations o ON om.organization_id = o.id
WHERE o.slug = $1 AND om.account_id = $2 LIMIT 1
`

type GetOrganizationMembershipBySlugParams struct {
	Slug      string
	AccountID int32
}

func (q *Queries) GetOrganizationMembershipBySlug(ctx context.Context, arg GetOrganizationMembershipBySlugParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipBySlug, arg.Slug, arg.AccountID)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_membership
WHERE organization_id = $1 AND account_id = $2
`

type RemoveOrganizationMemberParams struct {
	OrganizationID int32
	AccountID      int32
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, arg.OrganizationID, arg.AccountID)
	return err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :exec
UPDATE organization_membership
SET role = $3, updated_at = now()
WHERE organization_id = $1 AND account_id = $2
`

type UpdateOrganizationMemberRoleParams struct {
	OrganizationID int32
	AccountID      int32
	Role           string
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationMemberRole, arg.OrganizationID, arg.AccountID, arg.Role)
	return err
}
